GET http://localhost:8080/api/recipes
Accept: application/json

###
POST http://localhost:8080/api/recipes
Content-Type: application/json

{
  "userId": 1,
  "name": "Recipe for cookies",
  "shortDescription": "description how to make cookies",
  "cookingTimeMinutes": 60,
  "products": [
    "test",
    "anotherTest",
    "andAnotherAnotherTEST"
  ],
  "image": "URLOFREADYCOOKIE",
  "longDescription": "This is a long description",
  "tags": [
    "sladko",
    "kruglo",
    "vkusno"
  ]
}
###
POST http://localhost:8080/api/recipes
Content-Type: application/json

{
  "userId": 2,
  "name": "Recipe for bread",
  "shortDescription": "description how to make cookies",
  "cookingTimeMinutes": 60,
  "products": [
    "test",
    "anotherTest",
    "andAnotherAnotherTEST"
  ],
  "image": "URLOFREADYCOOKIE",
  "longDescription": "This is a long description",
  "tags": [
    "hlqb",
    "zele",
    "maq"
  ]
}

###
DELETE http://localhost:8080/api/recipes/2

###

PUT http://localhost:8080/api/recipes/7
Content-Type: application/json

{
  "id": 7,
  "userId": 1,
  "name": "Recipe for cookies",
  "shortDescription": "Changed description",
  "cookingTimeMinutes": 10,
  "products": [
    "test",
    "anotherTest",
    "NONEEEEEEE"
  ],
  "image": "URLOFREADYCOOKIE",
  "longDescription": "This is a long description",
  "tags": [
    "sladko",
    "krugloeeeeeeeeeeeeeeeeee",
    "vkusno"
  ]
}
###
GET http://localhost:8080/api/recipes?tags=java
Content-Type: application/json

###
GET http://localhost:8080/api/recipes?name=one
Content-Type: application/json

###
POST http://localhost:8080/api/recipes
Content-Type: application/json

{




  "products": [
    "test",
    "anotherTest",
    "andAnotherAnotherTEST"
  ],
  "image": "URLOFREADYCOOKIE",
  "longDescription": "This is a long description",
  "tags": [
    "hlqb",
    "zele",
    "maq"
  ]
}
